[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundle = true
  external_node_modules = ["@nestjs/microservices", "@nestjs/websockets", "cache-manager", "class-transformer"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/lambda"
  status = 200