[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "dist"
  included_files = ["dist/**/*.js"] 

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/lambda"
  status = 200
