[build]
  command = "npm run build"
  publish = "dist"

[functions]
  # Aquí corregimos la jerarquía para que sea un objeto válido
  node_bundle = true
  external_node_modules = [
    "@nestjs/microservices", 
    "@nestjs/websockets", 
    "cache-manager", 
    "class-transformer",
    "class-validator"
  ]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/lambda"
  status = 200