[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  external_node_modules = [
    "class-transformer/storage",
    "@nestjs/microservices",
    "@nestjs/websockets",
    "@grpc/grpc-js",
    "@grpc/proto-loader",
    "kafkajs",
    "mqtt",
    "amqplib",
    "amqp-connection-manager",
    "redis",
    "ioredis",
    "nats",
    "cache-manager",
    "class-validator",
    "class-transformer"
  ]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200